### ISSUE TITLE
QnA Maker gives different scores on each Training

### ISSUE THREAD

**Issue by wickkiey** [Azure-Samples/cognitive-services-qnamaker-nodejs#12]
I am using QnA Maker with nodejs. 

Steps to reproduce, In the created KB

_Add a file -> Save and Train
Test with random text 

remove file -> Save and Train

Again add the same file -> Save and Train
Test same chars <scores are different from the first one>_

Is there anything I can do to  get same score, or is this expected one ?

**Comment by diberry** [comment]
@vivek1may Please post this question on StackOverflow and post a link to the SO question here.

**Comment by vivek1may** [comment]
Posting the SO link for the same. 

https://stackoverflow.com/questions/59025747/qna-maker-gives-different-scores-on-each-training

**Comment by diberry** [comment]
Looks like you have an answer on StackOverflow so closing this.
