### ISSUE TITLE
Qna maker returns answers with high confidence scores for values like "abcd" which is not in KB, for which azure search also returns null

### ISSUE THREAD

**Issue by ShirinKariappa** [Azure-Samples/cognitive-services-qnamaker-nodejs#14]
**user query:**
{
    "question": "abcd",
    "top": 20
}

**response from qna maker:**
{
            "questions": [
                "How do I add my account?",
            ],
            "answer": "In portal, login and add account",
            "score": 81.11
        }

for the same query, azure search to which this qna app is linked  doesn't return any answer.
If there are no records returned from azure search, how is qna maker portal displaying the answer? Is Qna performing some spell check and mapping "abcd" as "add" in the above query?

**Comment by diberry** [comment]
Please open a support ticket for this issue.
