### ISSUE TITLE
Train Api call to add suggestions to the QnA maker knowledgebase using nodejs doesn't work; gives bad request (400)

### ISSUE THREAD

**Issue by ShirinKariappa** [Azure-Samples/cognitive-services-qnamaker-nodejs#15]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Call the QnA maker train api function to send feedback to QnA maker, using nodejs.
qnaMaker.callTrainAsync(feedbackRecords)

### Any log messages given by the failure
>Request failed, returning bad request 400

### Expected/desired behavior
>Status code: 204 , success

### OS and Version?
> Windows 10

### Versions
>nodejs version v10.16.3
"botbuilder": "~4.5.1",
"botbuilder-ai": "~4.5.1",
"botbuilder-azure": "^4.8.0",
 "botbuilder-dialogs": "~4.5.1",
 "botbuilder-testing": "~4.5.1",

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Through Postman the below payload is working fine:
{
  "feedbackRecords": [
    {
      "userId": "sd53lsY=",
      "userQuestion": "qna maker with luis",
      "qnaId": 4
    }
  ]
}
>But in nodejs, the qnaMaker.callTrainAsync(feedbackRecords) function is sending below payload and is throwing bad request 400 error.

{"feedbackRecords":{
 "feedbackRecords": [
    {
      "userId": "sd53lsY=",
      "userQuestion": "qna maker with luis",
      "qnaId": 4
    }
  ]
}}

**Comment by diberry** [comment]
This appearts to be a bot framework issue. Please log your issue with that NPM module.
